[package]
name = "HyPortal"
version = "0.1.0"
edition = "2021"
description = "HyPortal - an unofficial Hytale launcher"
default-run = "HyPortal"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", features = ["tls"], default-features = false }
igd-next = "0.15"
sha2 = "0.10"
getrandom = "0.2"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
